//    "hack400tool"
//    - security handling tools for IBM Power Systems (formerly known as AS/400)
//    Copyright (C) 2010-2017  Bart Kulach
//    This file, ScanUI.java, is part of hack400tool package.

//    "hack400tool" is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.

//    "hack400tool" is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.

//   You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
package org.hackthelegacy.hack400tool.ibmiscannergui;

import org.hackthelegacy.hack400tool.ibmiscannergui.TextAreaOutputStream;
import com.ibm.as400.access.ObjectList;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.hackthelegacy.hack400tool.ibmiscannercore.IBMiConnector;
import org.hackthelegacy.hack400tool.ibmiscannercore.SqliteDbConnector;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.net.ssl.SSLHandshakeException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class ScanUI extends javax.swing.JFrame {

    private IBMiConnector testSystem;
    public SqliteDbConnector dbConnection;
    private ByteArrayOutputStream bstdout, bstderr;
    private PrintStream stdouterr;
    private String jarPath;
    private File jarFile;
    
    /**
     * Creates new form APIsetup
     */
    public ScanUI() throws IOException {
        jarFile = new File(ScanUI.class.getProtectionDomain().getCodeSource().getLocation().getPath());
        jarPath = jarFile.getParentFile().getPath();
        initComponents();
        String fileName = new SimpleDateFormat("YYMMddHHmmSS").format(new Date());
        stdouterr = new PrintStream(new TextAreaOutputStream(logTextArea, "", jarPath 
                                    + File.separator + "log" + File.separator + fileName + ".log"));
        System.setErr(stdouterr);
        System.setOut(stdouterr);       

        Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, jarPath);
        
        
        dbConnection = new SqliteDbConnector("IBMiScanner.db");        
        try {
            DefaultTableModel tableModel = dbConnection.query("SELECT id AS 'ID', description AS 'Description' FROM settingdetails;").toTableModel();
            settingsTable.setModel(tableModel);
            settingsTable.getColumnModel().getColumn(0).setResizable(false);
            settingsTable.getColumnModel().getColumn(0).setMaxWidth(30);
            settingsTable.getColumnModel().getColumn(1).setResizable(false);            
            
        } catch (Exception ex) {
            Logger.getLogger(ScanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex){

        }
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        settingsTable = new javax.swing.JTable();
        selectAllButton = new javax.swing.JButton();
        deselectAllButton = new javax.swing.JButton();
        scanButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        outputDirFolderTextField = new javax.swing.JTextField();
        createSubfolderCheckBox = new javax.swing.JCheckBox();
        browseDirsButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        escalateToTextField = new javax.swing.JTextField();
        escalateButton = new javax.swing.JButton();
        DeescalateButton = new javax.swing.JButton();
        escalateToComboBox = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        systemName = new javax.swing.JTextField();
        userNameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        disconnectButton = new javax.swing.JButton();
        temporaryLibTextField = new javax.swing.JTextField();
        proxyTextField = new javax.swing.JTextField();
        useProxy = new javax.swing.JCheckBox();
        useJDBC = new javax.swing.JCheckBox();
        useSSL = new javax.swing.JCheckBox();
        useSockets = new javax.swing.JCheckBox();
        useGUI = new javax.swing.JCheckBox();
        useNetSockets = new javax.swing.JCheckBox();
        connectButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane2.setViewportView(logTextArea);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/hack400scanner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tests to be performed"));

        settingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        settingsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(settingsTable);
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.blue);

        for (int i = 0; i < settingsTable.getModel().getColumnCount(); i++) {
            settingsTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        selectAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Checked Checkbox_20px.png"))); // NOI18N
        selectAllButton.setText("Select all");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        deselectAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Unchecked Checkbox_20px.png"))); // NOI18N
        deselectAllButton.setText("Deselect all");
        deselectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deselectAllButtonActionPerformed(evt);
            }
        });

        scanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Exercise_20px.png"))); // NOI18N
        scanButton.setText("Run scan");
        scanButton.setEnabled(false);
        scanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(selectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deselectAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(scanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(selectAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deselectAllButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(scanButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        outputDirFolderTextField.setText(jarPath + File.separator + "output");

        createSubfolderCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        createSubfolderCheckBox.setSelected(true);
        createSubfolderCheckBox.setText("Create new subfolder for the scanned machine (folder name = system name)");

        browseDirsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Open Folder_20px.png"))); // NOI18N
        browseDirsButton.setText("Browse...");
        browseDirsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseDirsButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Directory to store output:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(createSubfolderCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(outputDirFolderTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(browseDirsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputDirFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseDirsButton)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addComponent(createSubfolderCheckBox))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Use escalated privileges"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Synchronize_20px.png"))); // NOI18N
        jButton1.setText("Get escalation users");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Escalate to:");

        escalateToTextField.setText("QSECOFR");

        escalateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Escalator Up_20px.png"))); // NOI18N
        escalateButton.setText("Escalate");
        escalateButton.setEnabled(false);
        escalateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalateButtonActionPerformed(evt);
            }
        });

        DeescalateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Escalator Down_20px.png"))); // NOI18N
        DeescalateButton.setText("Deescalate");
        DeescalateButton.setEnabled(false);
        DeescalateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeescalateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escalateToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(escalateToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeescalateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(escalateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(escalateToTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(escalateToComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(escalateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeescalateButton)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        systemName.setNextFocusableComponent(userNameField);

        userNameField.setNextFocusableComponent(passwordField);

        passwordField.setNextFocusableComponent(temporaryLibTextField);

        disconnectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Disconnected_20px.png"))); // NOI18N
        disconnectButton.setText("Disconnect");
        disconnectButton.setEnabled(false);
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        temporaryLibTextField.setText("QTEMP");
        temporaryLibTextField.setNextFocusableComponent(proxyTextField);

        useProxy.setBackground(new java.awt.Color(255, 255, 255));
        useProxy.setText("Use proxy");

        useJDBC.setBackground(new java.awt.Color(255, 255, 255));
        useJDBC.setText("Use JDBC");

        useSSL.setBackground(new java.awt.Color(255, 255, 255));
        useSSL.setText("Use SSL");

        useSockets.setBackground(new java.awt.Color(255, 255, 255));
        useSockets.setText("Use Sockets");

        useGUI.setBackground(new java.awt.Color(255, 255, 255));
        useGUI.setText("Use login GUI");

        useNetSockets.setBackground(new java.awt.Color(255, 255, 255));
        useNetSockets.setText("Use NetSockets");

        connectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Connected_20px.png"))); // NOI18N
        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Proxy IP or DNS:");

        jLabel9.setText("Username:");

        jLabel10.setText("Password:");

        jLabel8.setText("Temporary library:");

        jLabel2.setText("IP address or DNS name:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Asterisk_10px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Asterisk_10px.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/hackthelegacy/hack400tool/ibmiscannergui/Asterisk_10px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systemName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temporaryLibTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(useSSL, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(useGUI))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(useNetSockets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(useSockets, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(useProxy)
                        .addGap(18, 18, 18)
                        .addComponent(useJDBC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(proxyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disconnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(connectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disconnectButton))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(systemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(proxyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(temporaryLibTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(useProxy)
                                    .addComponent(useJDBC))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(useSSL)
                                    .addComponent(useSockets))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(useGUI)
                                    .addComponent(useNetSockets))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
    if (!disconnectButton.isEnabled()) return;
    
    try {
            testSystem.disconnect();
        } catch (Exception ex) {
            Logger.getLogger(ScanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        try {
            testSystem.disconnect();
        } catch (Exception ex) {
            Logger.getLogger(ScanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        connectButton.setEnabled(true);
        disconnectButton.setEnabled(false);
        scanButton.setEnabled(false);
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        final SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    connectButton.setEnabled(false);
                    String passwordString = new String(passwordField.getPassword());
                    if (useProxy.isSelected()) {
                        testSystem = new IBMiConnector(systemName.getText(), useSSL.isSelected(), useJDBC.isSelected(), 
                                useGUI.isSelected(), useSockets.isSelected(), useNetSockets.isSelected(),
                            temporaryLibTextField.getText(), userNameField.getText(),
                            passwordString, true, proxyTextField.getText());
                    }
                    else {            
                        testSystem = new IBMiConnector(systemName.getText(), useSSL.isSelected(), useJDBC.isSelected(), 
                                useGUI.isSelected(), useSockets.isSelected(), useNetSockets.isSelected(),
                            temporaryLibTextField.getText(), userNameField.getText(),
                            passwordString);
                    }
                } catch (Exception ex) {
                    Logger.getLogger(ScanUI.class.getName()).log(Level.SEVERE, null, ex);
                    connectButton.setEnabled(true);
                    return null;
                }
                disconnectButton.setEnabled(true);
                connectButton.setEnabled(false);
                if (settingsTable.getSelectedRowCount() > 0)
                scanButton.setEnabled(true);
                escalateButton.setEnabled(true);        

                return null;
            }
        };

        mySwingWorker.addPropertyChangeListener(new PropertyChangeListener() {
           public void propertyChange(PropertyChangeEvent evt) {
           }
        });
        mySwingWorker.execute();

        
    }//GEN-LAST:event_connectButtonActionPerformed

    private void deselectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deselectAllButtonActionPerformed
        settingsTable.clearSelection();
        scanButton.setEnabled(false);
    }//GEN-LAST:event_deselectAllButtonActionPerformed

    private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
        settingsTable.selectAll();
        if (disconnectButton.isEnabled())
        scanButton.setEnabled(true);
    }//GEN-LAST:event_selectAllButtonActionPerformed

    private void settingsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsTableMouseClicked
        if (settingsTable.getSelectedRowCount() > 0 && disconnectButton.isEnabled())
        scanButton.setEnabled(true);
    }//GEN-LAST:event_settingsTableMouseClicked

    private void browseDirsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDirsButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save");
        fileChooser.setSelectedFile(new File(outputDirFolderTextField.getText()));
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setMultiSelectionEnabled(false);

        int folderSelection = fileChooser.showSaveDialog(this);

        if (folderSelection == JFileChooser.APPROVE_OPTION) {
            File dirToSave = fileChooser.getSelectedFile();
            outputDirFolderTextField.setText(dirToSave.getAbsolutePath());
        }
    }//GEN-LAST:event_browseDirsButtonActionPerformed

    private void scanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanButtonActionPerformed

        /* Definitions from table settingdetails:
        function_type::={API,CLCMD,SHELLCMD, method}
        output_type::={PRINT,OUTFILE,STMF_TEXT, STMF_BIN,stdout, binary, <function call>}

        CLCMD + PRINT: output_params::=SPLF name
        CLCMD + OUTFILE: output_params::=LIB/FILE(MBR)
        CLCMD + STMF_BIN,STMF_TEXT: output_params::=/path/to/file
        API + BIN: output_params::=<parsing methods>
        METHOD + <output_function>: output_params::= <class for output cast>
        SHELLCMD + STMF_BIN,STMF_TEXT: output_params::=/path/to/file
        SHELLCMD + STDOUT: output_params::=<null>
        */
        if (settingsTable.getSelectedRowCount() < 1 || outputDirFolderTextField.getText() == "") {
            JOptionPane.showMessageDialog(null, "The path is not correct or no scan settings were selected!", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        final String outputDirectory = (createSubfolderCheckBox.isSelected() ? 
                                    outputDirFolderTextField.getText() + File.separator + systemName.getText() : 
                                    outputDirFolderTextField.getText());
        
        scanButton.setEnabled(false);
        final SwingWorker<Void, Void> mySwingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                try {
                    Thread runThread = new Thread() {
                        public void run() {
                            Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, "Initializing scan...");
                            try {
                                for (int selectedRow : settingsTable.getSelectedRows()) {
                                    DefaultTableModel detailSettings = dbConnection.query(
                                        "SELECT function_type, function_call, num_input_params, input_params,"
                                        + "output_type, output_params, output_filename FROM settingdetails WHERE id='"
                                        + settingsTable.getModel().getValueAt(selectedRow, 0).toString() + "'").toTableModel();
                                    if (detailSettings.getRowCount() < 1) {
                                        JOptionPane.showMessageDialog(null, "Error occured while getting details of scan parameters from the database", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
                                        return;
                                    }
                                        Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, "Running scan: "
                                            + (String)settingsTable.getModel().getValueAt(selectedRow, 1));
                                        switch (((String)detailSettings.getValueAt(0, 0)).toUpperCase()) /*function_type*/ {
                                            case "CLCMD":
                                                Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, "Running command " + (String)detailSettings.getValueAt(0, 1));
                                                String outputMessages = testSystem.runCLCommand(
                                                    (String)detailSettings.getValueAt(0, 1) +
                                                    ((int)detailSettings.getValueAt(0, 2) == 0 ? "" :
                                                        (" " + (String)detailSettings.getValueAt(0, 3)))); /*function_call*/
                                                Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, outputMessages);
                                                switch (((String)detailSettings.getValueAt(0, 4)).toUpperCase()) /*output_type*/{
                                                    case "PRINT": /*output_params*/
                                                    testSystem.getSpoolFileToDOCX(outputDirectory + File.separator + 
                                                        systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                        (String)detailSettings.getValueAt(0, 5));
                                                    break;
                                                    case "OUTFILE":
                                                    testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                        systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                        testSystem.getPhysicalFileMemberAsTable2((String)detailSettings.getValueAt(0, 5)));
                                                    break;
                                                    case "STMF_TEXT":
                                                    testSystem.exportToDOCX(outputDirectory + File.separator + 
                                                        systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                        testSystem.getIFSTextFile((String)detailSettings.getValueAt(0, 5)));
                                                    break;
                                                    case "STMF_BIN":
                                                    testSystem.exportToBinaryFile(outputDirectory + File.separator + 
                                                        systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                        testSystem.getIFSBinaryFile((String)detailSettings.getValueAt(0, 5)));
                                                    break;
                                                    default:
                                                    testSystem.exportToDOCX(outputDirectory + File.separator + 
                                                        systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                        outputMessages);
                                                    break;
                                                }
                                                break;
                                                case "SHELLCMD":
                                                    /*Not supported yet*/
                                                break;
                                                case "METHOD":
                                                    Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, "Running method " + (String)detailSettings.getValueAt(0, 1));
                                                    switch ((String)detailSettings.getValueAt(0, 1)) {
                                                        case "getAuthorisationMatrix":
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getAuthorisationMatrix2());
                                                        break;
                                                        case "getAllSystemValues":
                                                        testSystem.exportToXLSX(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getAllSystemValues());
                                                        break;
                                                        case "getAllAuthorisationLists":
                                                        testSystem.exportToXLSX(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getAllAuthorisationLists());
                                                        break;
                                                        case "getAllLibraries":
                                                        testSystem.exportToXLSX(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getAllLibraries());
                                                        break;
                                                        case "getAllQSYSCommands":
                                                        testSystem.exportToXLSX(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getAllQSYSCommands());
                                                        break;
                                                        case "getAllFolderFiles":
                                                        testSystem.exportToXLSX(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getAuthoritiesForObjects(ObjectList.ALL, (String)detailSettings.getValueAt(0, 3), "*FILE"));
                                                        break;
                                                        case "getPhysicalFile":
                                                        testSystem.exportToXLSX(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getPhysicalFileMemberAsTable((String)detailSettings.getValueAt(0, 3)));
                                                        break;
                                                        case "getJohnPasswordsLM":
                                                        testSystem.getJohnPasswordsLM(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6));
                                                        break;
                                                        case "getJohnPasswordsDES":
                                                        testSystem.getJohnPasswordsDES(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6));
                                                        break;
                                                        case "getJohnPasswordsSHAUpperCase":
                                                        testSystem.getJohnPasswordsSHAUpperCase(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6));
                                                        break;
                                                        case "getJohnPasswordsSHAMixedCase":
                                                        testSystem.getJohnPasswordsSHAMixedCase(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6));
                                                        break;
                                                        case "getExitPointInfo":
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getExitPointInfo());
                                                        break;
                                                        case "getFunctionUsageInfo":
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getFunctionUsageInfo());
                                                        break;
                                                        case "getPTFs":
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getPTFs2());
                                                        break;
                                                        case "netStat":                            
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getNetStat()); 
                                                            break;
                                                        case "getNetIfaces":                            
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getNetIfaces()); 
                                                            break;
                                                        case "getNetRoutes":                            
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getNetRoutes()); 
                                                            break;
                                                        case "getSMBShares":                            
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getSMBShares()); 
                                                            break;
                                                        case "getNFSShares":                            
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getNFSShares()); 
                                                            break;
                                                        case "getARPTable":                            
                                                            testSystem.exportToXLSX2(outputDirectory + File.separator + 
                                                            systemName.getText() + "-" + (String)detailSettings.getValueAt(0, 6),
                                                            testSystem.getARPTable()); 
                                                            break;
                                                        default:
                                                        break;
                                                    }
                                                    default:
                                                    case "API":
                                                    break;
                                                }
                                                    Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, "Done ("
                                                        + (String)settingsTable.getModel().getValueAt(selectedRow, 1) + ")");
                                                }

                                                Logger.getLogger(ScanUI.class.getName()).log(Level.INFO, "Test finished. Check directory "
                                                    + outputDirectory + " for output files.");

                                                testSystem.exportToDOCX(outputDirectory + File.separator + "joblog.docx",
                                                    testSystem.getJobLog()
                                                    + "\n\nSTDOUT + STDERR:\n\n" + logTextArea.getText());

                                                scanButton.setEnabled(true);
                                            } catch (Exception ex) {
                                                Logger.getLogger(ScanUI.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        }
                        };
                    runThread.start();
                } catch (Exception ex) {
                    Logger.getLogger(HackUI.class.getName()).log(Level.SEVERE, null, ex);
                    connectButton.setEnabled(true);
                    disconnectButton.setEnabled(false);
                }                    
                return null;
            }
        };

        mySwingWorker.addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
            }
        });
        mySwingWorker.execute();

    }//GEN-LAST:event_scanButtonActionPerformed

    private void escalateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalateButtonActionPerformed
        try {
            DeescalateButton.setEnabled(testSystem.escalatePrivilegeWithoutPassword(escalateToTextField.getText(), IBMiConnector.PASSWORD_TYPE_NOPWD));
        } catch (Exception ex) {
            Logger.getLogger(HackUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_escalateButtonActionPerformed

    private void DeescalateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeescalateButtonActionPerformed
        try {
            DeescalateButton.setEnabled(testSystem.deescalatePrivileges());       
        } catch (Exception ex) {
            Logger.getLogger(HackUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeescalateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            escalateToComboBox.setModel(new DefaultComboBoxModel(testSystem.getEscalationUsers().toArray()));
        } catch (Exception ex) {
            Logger.getLogger(HackUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ScanUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ScanUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeescalateButton;
    private javax.swing.JButton browseDirsButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JCheckBox createSubfolderCheckBox;
    private javax.swing.JButton deselectAllButton;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton escalateButton;
    private javax.swing.JComboBox escalateToComboBox;
    private javax.swing.JTextField escalateToTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JTextField outputDirFolderTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField proxyTextField;
    private javax.swing.JButton scanButton;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JTable settingsTable;
    private javax.swing.JTextField systemName;
    private javax.swing.JTextField temporaryLibTextField;
    private javax.swing.JCheckBox useGUI;
    private javax.swing.JCheckBox useJDBC;
    private javax.swing.JCheckBox useNetSockets;
    private javax.swing.JCheckBox useProxy;
    private javax.swing.JCheckBox useSSL;
    private javax.swing.JCheckBox useSockets;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
